### ISSUE TITLE
coverage

### ISSUE THREAD

**Issue by marutosi** [naitoh/rbpdf#22]
多分まともに動かないだろうとは思ってましたが、予想通りです。
https://github.com/marutosi/rbpdf/tree/codecov
https://travis-ci.org/marutosi/rbpdf/builds/70480551
https://codecov.io/github/marutosi/rbpdf?branch=codecov

**Comment by naitoh** [comment]
すみません、よくわかっていないのですが
「多分まともに動かないだろう」というのは、travis-ci の結果が ruby 1.9.2 で失敗しているからでしょうか？
それとも、codecovの結果がCoverage 59.07%とテストカバレージが低いことを言われているのでしょうか？
カバレージは低いかな？とは思っていましたが、数値で見えて納得しました。
とりあえず、カバレージは80%ぐらいは目指したいですね。

**Comment by marutosi** [comment]
あと肝心要のこのページが開きません。
https://codecov.io/github/marutosi/rbpdf/lib/rbpdf.rb?ref=codecov

**Comment by marutosi** [comment]
フォーク先のリポジトリを削除するので、
838341d18417de3d0 へのパッチです。

[codecov.txt](https://github.com/naitoh/rbpdf/files/4186154/codecov.txt)
