### ISSUE TITLE
rbpdf causes "RMagick" deprecation warning in rake tasks ?

### ISSUE THREAD

**Issue by gc-olivierho** [naitoh/rbpdf#28]
Whenever I run a rake command from the prompt, I get the message:
  [DEPRECATION] requiring "RMagick" is deprecated. Use "rmagick" instead

I do have rmagick gem 2.15.4, rbpdf 1.18.6 in my gems, and "bundle install" tells me I'm using those versions.

I tried removing line 64 of file /usr/local/rvm/gems/ruby-2.0.0-p247/gems/rbpdf-1.18.6/lib/rbpdf.rb, and the warning does go away.

However, on my test machine, I don't have the warning even though I did not touch the rbpdf gem.

I really wonder why there is a difference between my test machine and my production server, but anyway, I can't keep that warning popping up, because it generates mails for all my cron rake tasks, even though they are successful, which creates tons of useless mails (I run rake tasks for checking incoming mails every 5 minutes).

So:
1) Should rbpdf really try to load "RMagick" if it failed loading "rmagick" ?
2) Would you have any hint on why rmagick would be loaded in one of my rake environments and not in the other?

I'm using Linux centOS, and the test machine is originally a copy of the production machine, on which I only updated gems and Rails regularly. The server is used for hosting a Redmine web site (so it has Ruby on Rails and Redmine).

Best regards,
Olivier
PS : if you want me to run some tests on the machine popping up the warning, I can do it.

**Comment by marutosi** [comment]
> I tried removing line 64 of file /usr/local/rvm/gems/ruby-2.0.0-p247/gems/rbpdf-1.18.6/lib/rbpdf.rb, and the warning does go away.

Really?
https://github.com/naitoh/rbpdf/blob/1.18.6/lib/rbpdf.rb#L64

**Comment by gc-olivierho** [comment]
Sorry, this is line 67, not 64.

**Comment by marutosi** [comment]
If you use "rake" in your cron, try "bundle exec rake" instead.

**Comment by gc-olivierho** [comment]
![rmagick](https://cloud.githubusercontent.com/assets/5647124/11294750/2ec13cd8-8f66-11e5-9870-515bce9fbb98.png)
It did not help...

**Comment by marutosi** [comment]
What output "bundle show rbpdf" and " bundle show rmagick"?

**Comment by gc-olivierho** [comment]
on prod:
[root@rd-redmine]# bundle show rbpdf
/usr/local/rvm/gems/ruby-2.0.0-p247/gems/rbpdf-1.18.6
[root@rd-redmine]# bundle show rmagick
/usr/local/rvm/gems/ruby-2.0.0-p247/gems/rmagick-2.15.4

on test:
[root@rd-redmine-test redmine]# bundle show rbpdf
/usr/local/rvm/gems/ruby-2.0.0-p247/gems/rbpdf-1.18.6
[root@rd-redmine-test redmine]# bundle show rmagick
/usr/local/rvm/gems/ruby-2.0.0-p247/gems/rmagick-2.15.4

**Comment by marutosi** [comment]
What output?

```
$ gem list rmagick

*** LOCAL GEMS ***

rmagick (2.15.4, 2.15.3, 2.15.2, 2.13.4)


$ irb
1.9.3-p551 :001 > puts "defined" if Object.const_defined?(:Magick)
 => nil
1.9.3-p551 :002 > require 'rmagick'
 => true
1.9.3-p551 :003 > puts "defined" if Object.const_defined?(:Magick)
defined
 => nil
1.9.3-p551 :004 > quit


```

**Comment by gc-olivierho** [comment]
[root@rd-redmine log]# gem list rmagick
*** LOCAL GEMS ***
rmagick (2.15.4, 2.13.4, 2.13.3, 2.13.2)

and

[root@rd-redmine-test redmine]# gem list rmagick
*** LOCAL GEMS ***
rmagick (2.15.4, 2.14.0, 2.13.4, 2.13.3, 2.13.2)


and just in case:
[root@rd-redmine log]# gem list rbpdf
*** LOCAL GEMS ***
rbpdf (1.18.6, 1.18.4, 1.18.2)

[root@rd-redmine-test redmine]# gem list rbpdf
*** LOCAL GEMS ***
rbpdf (1.18.6, 1.18.5, 1.18.4, 1.18.1)

**Comment by marutosi** [comment]
What output?

```
$ irb
1.9.3-p551 :001 > puts "defined" if Object.const_defined?(:Magick)
 => nil
1.9.3-p551 :002 > require 'rmagick'
 => true
1.9.3-p551 :003 > puts "defined" if Object.const_defined?(:Magick)
defined
 => nil
1.9.3-p551 :004 > quit
```

**Comment by gc-olivierho** [comment]
[root@rd-redmine log]# irb
2.0.0-p247 :001 > puts "defined" if Object.const_defined?(:Magick)
  => nil
2.0.0-p247 :002 > require 'rmagick'
LoadError: libMagickCore.so.2: cannot open shared object file: No such 
file or directory - 
/usr/local/rvm/gems/ruby-2.0.0-p247/gems/rmagick-2.15.4/lib/RMagick2.so
         from 
/usr/local/rvm/rubies/ruby-2.0.0-p247/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:133:in 
`require'
         from 
/usr/local/rvm/rubies/ruby-2.0.0-p247/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:133:in 
`rescue in require'
         from 
/usr/local/rvm/rubies/ruby-2.0.0-p247/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:142:in 
`require'
         from 
/usr/local/rvm/gems/ruby-2.0.0-p247/gems/rmagick-2.15.4/lib/rmagick_internal.rb:12:in 
`<top (required)>'
         from 
/usr/local/rvm/rubies/ruby-2.0.0-p247/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:53:in 
`require'
         from 
/usr/local/rvm/rubies/ruby-2.0.0-p247/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:53:in 
`require'
         from 
/usr/local/rvm/gems/ruby-2.0.0-p247/gems/rmagick-2.15.4/lib/rmagick.rb:1:in 
`<top (required)>'
         from 
/usr/local/rvm/rubies/ruby-2.0.0-p247/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:133:in 
`require'
         from 
/usr/local/rvm/rubies/ruby-2.0.0-p247/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:133:in 
`rescue in require'
         from 
/usr/local/rvm/rubies/ruby-2.0.0-p247/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:142:in 
`require'
         from (irb):2
         from /usr/local/rvm/rubies/ruby-2.0.0-p247/bin/irb:13:in `<main>'
2.0.0-p247 :003 > puts "defined" if Object.const_defined?(:Magick)
  => nil

I do have that file, though :

**Comment by marutosi** [comment]
Your installation is broken. It is not rbpdf problem.
@naitoh, please close this issue.

**Comment by marutosi** [comment]
@gc-olivierho, you had better ask rmagick team.

**Comment by gc-olivierho** [comment]
Thank you very much for your analysis, I'll look on how to fix that on our side.

**Comment by gc-olivierho** [comment]
PS : I ran "gem uninstall rmagick" and re-installed, and it solved the issue.

**Comment by naitoh** [comment]
Thanks Toshi!
