### ISSUE TITLE
upgrade to  htmlentities 4.3.3

### ISSUE THREAD

**Issue by deogracia** [naitoh/rbpdf#29]
Hi,

Can you update htmlentities to 4.3.3 ?

I still got duplicated key warning like in https://github.com/threedaymonk/htmlentities/pull/17

Thanks :D

**Comment by naitoh** [comment]
> Can you update htmlentities to 4.3.3 ?

Sorry, htmlentities 4.3.3 is not support Ruby 1.8.7.

rbpdf is still supporting Ruby 1.8.7.

Thanks.

**Comment by deogracia** [comment]
Aaah, ok. Didn't pay attention to that part :'(
Thanks :D

**Comment by deltab** [comment]
Is it possible to allow 4.3.1 and later versions?

**Comment by amenk** [comment]
So why is it not upgraded?

**Comment by naitoh** [comment]
Sorry for my late response.
fixed 31a51c693511967e7b8904569ac5ade185137e8a
