### ISSUE TITLE
unclear license information

### ISSUE THREAD

**Issue by terceiro** [naitoh/rbpdf#32]
Hi,

I am packaging rbpdf for Debian as a dependency of redmine, but the licensing information in the source tree is very confusing.

In the git repository, `LICENSE.TXT` says LGPL, `MIT-LICENSE` says "MIT license". Can you please clarify exactly what parts are under the LGPL, and what parts are under the MIT license?

Also, in the `.gem` file thats is actually distributed via rubygems.org, only `LICENSE.TXT` is shipped.

**Comment by naitoh** [comment]
I updated license information.
Please see README.md, rbpdf-font/README.md.

**Comment by terceiro** [comment]
hi, sorry for not mentniong, but I would need an explicit copyright statement for the files that don't have one already.

Also, about the font files: your commit mentions they are not required, if those fonts are installed system-wide, will rbpdf be able to find and use them? Debian already has most if not all of those fonts so would like to not duplicate them.

**Comment by naitoh** [comment]
Sorry for my late response.

> hi, sorry for not mentniong, but I would need an explicit copyright statement for the files that don't have one already.

OK, I will think about it.

> your commit mentions they are not required, if those fonts are installed system-wide, will rbpdf be able to find and use them?

No.

> Debian already has most if not all of those fonts so would like to not duplicate them.

I do not know how to support unknown system font files.

**Comment by naitoh** [comment]
fixed 5c156e1b44ec69b55d1fc42a09308e78c4b92f6f
