### ISSUE TITLE
Strict htmlentities dependencie causes warning

### ISSUE THREAD

**Issue by margusnomme** [naitoh/rbpdf#33]
`rbpdf` gem has strict dependcy 
`"htmlentities" "=4.3.1"`

Unfortunately [htmlentitie](https://github.com/threedaymonk/htmlentities) has error in versions **4.3.1** and **4.3.2** where in file `lib/htmlentities/mappings/expanded.rb` key **inodot** is defined twice. This error is removed in tag **4.3.3**.

**Comment by stefan-hausmann** [comment]
+1

**Comment by will-in-wi** [comment]
There is a PR that somewhat addresses this here: https://github.com/naitoh/rbpdf/pull/35

**Comment by marutosi** [comment]
+1
http://www.redmine.org/issues/24271

**Comment by n-rodriguez** [comment]
Hi! any news?

**Comment by naitoh** [comment]
Sorry for my late response.
fixed 31a51c693511967e7b8904569ac5ade185137e8a
