### ISSUE TITLE
Typo in rbpdf.rb?

### ISSUE THREAD

**Issue by nanego** [naitoh/rbpdf#36]
In the rbpdf.rb file, we are using curly brackets {} instead of brackets [] to access second character of a string: https://github.com/naitoh/rbpdf/blob/master/lib/rbpdf.rb#L11033

```
if attrib{1} == ':'  # pseudo-element
          # pseudo-elements are not supported!
          # (::first-line, ::first-letter, ::before, ::after)
        else # pseudo-class
```

Do you know why? This cause an error on my app.

```
[1] pry(main)> s = "test"
=> "test"
[2] pry(main)> s[1]
=> "e"
[3] pry(main)> s{1}
NoMethodError: undefined method `s' for main:Object
```

**Comment by naitoh** [comment]
Sorry for my late response.
Thank you very much for your pull request!
