### ISSUE TITLE
backslashes are duplicated in a table

### ISSUE THREAD

**Issue by t-gergely** [naitoh/rbpdf#39]
<td>\</td> shows as \\.
There's some replacing of backslashes that I don't understand, but the attached patch shows where the problem is.
[rbpdf.patch.txt](https://github.com/naitoh/rbpdf/files/783498/rbpdf.patch.txt)

**Comment by naitoh** [comment]
Thank you for patch.

fixed 0932ec03c8f2f4ab14db0c273ba1b244e78eb931
