### ISSUE TITLE
Inifite loop

### ISSUE THREAD

**Issue by salmanmp** [naitoh/rbpdf#62]
When try to export some html text that contains <img> tag with invalid src attribute, it is gone into infinit loop.
May be this line causes that infinite loop.
https://github.com/naitoh/rbpdf/blob/838341d18417de3d0b5d4c832a23859c01e55328/lib/rbpdf.rb#L12173

**Comment by skalimer0** [comment]
Hello,

It's not invalid src attribute the problem but the width of the image who need new linebreak to format the document.
The key-- it's to evaluate the new line break... but this one are not detected and method make infite loop on line 12173.

**Comment by skalimer0** [comment]
A solution is to check imgw and if it's too bigger using 100% rendering

**Comment by salmanmp** [comment]
> It's not invalid src attribute the problem but the width of the image who need new linebreak to format the document.
Probabely both of them. I tested that situation.
Thanks.

**Comment by skalimer0** [comment]
i fork the project and patch it for the oversize infinite loop on line 12173

**Comment by salmanmp** [comment]
Is it going to update  gem on rubygems.org?

**Comment by naitoh** [comment]
please use https://rubygems.org/gems/rbpdf/versions/1.21.0

**Comment by salmanmp** [comment]
I tested with an invalid src attribute and unfortunately infinite loop was occurred!
something like `<img src="/system/files/not-exist-file.png">`

**Comment by naitoh** [comment]
> I tested with an invalid src attribute and unfortunately infinite loop was occurred!
> something like `<img src="/system/files/not-exist-file.png">`

@salmanmp 

I can't reproduce it in my environment.

```Ruby
$ irb
> require 'rbpdf'
> pdf = RBPDF.new
> pdf.add_page
> pdf.write_html('<img src="/system/files/not-exist-file.png">')
E, [2023-02-25T20:49:32.257183 #37955] ERROR -- : pdf: Image: error: RBPDF error: Image file is not found. : /system/files/not-exist-file.png
=> nil
> pdf.write_html('<html><body><img src="/system/files/not-exist-file.png"></body></html>')
E, [2023-02-25T20:52:38.317192 #37988] ERROR -- : pdf: Image: error: RBPDF error: Image file is not found. : /system/files/not-exist-file.png
=> nil
```

### My Environment: Ruby 3.1.2, no rmagick, no mini_magick. 

```sh
$ ruby -v
ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [arm64-darwin21]
$ gem list |grep magick
$
$ gem list rbpdf

*** LOCAL GEMS ***

rbpdf (1.21.0)
rbpdf-font (1.19.1)
```

**Comment by salmanmp** [comment]
I tested again and could not reproduce that bug. Thank you.

**Comment by salmanmp** [comment]
Hi again
I found the scenario that makes an infinit loop!

```Ruby
#irb
html = '<p><img src="/somewhere/image.png" style="width:2000px;height:563px;"></p>'
r = RBPDF.new
r.add_page
r.set_rtl(true)
r.writeHTMLCell(0, 0, "", "", html)
```
If you decerase `width` to `1000px` it works fine.

As I mentioned at the first message it is related to this code block in `rbpdf.rb`. But it's not related to `src` and existance of image, but related to oversize of image (that @skalimer0 told before :+1: ).

```Ruby
if (@rtl and (@x - imgw < @l_margin + @c_margin)) or (!@rtl and (@x + imgw > @w - @r_margin - @c_margin))
    # add automatic line break
    autolinebreak = true
    Ln('', cell)
    # go back to evaluate this line break
    key -= 1
end
```
