### ISSUE TITLE
Redmine 4.2.1 error export to pdf

### ISSUE THREAD

**Issue by zakachkin** [naitoh/rbpdf#63]
Нelp me please
`Started GET "/projects/smartool-dposm/wiki.pdf?utf8=%E2%9C%93&pdf%5Borientation%5D=1" for 95.221.54.79 at 2022-01-20 06:19:20 +0300
Processing by WikiController#show as PDF
  Parameters: {"utf8"=>"✓", "pdf"=>{"orientation"=>"1"}, "project_id"=>"smartool-dposm"}
  Current user: viktordemo (id=51)
  Rendering wiki/show.pdf.erb
Deface: 'wiki-show-bottom' matched 0 times with 'p.wiki-update-info'
  Rendered wiki/show.pdf.erb (143.8ms)
Completed 500 Internal Server Error in 167ms (ActiveRecord: 3.8ms)

ActionView::Template::Error (RBPDF error: Unsupported image type: webp):
    1: <%= raw wiki_page_to_pdf(@page, @project) %>

plugins/redmine_reporting/app/models/reporting_pdf/pdf_renderer.rb:127:in `render_pdf_header'
plugins/redmine_reporting/app/models/reporting_pdf/pdf_renderer.rb:88:in `make_pdf'
plugins/redmine_reporting/app/helpers/reporting_export_helper.rb:57:in `reporting_make_pdf'
plugins/redmine_reporting/app/helpers/reporting_export_helper.rb:94:in `wiki_page_to_pdf'
app/views/wiki/show.pdf.erb:1:in `_app_views_wiki_show_pdf_erb___1217950578384769169_47286679215120'
plugins/redmine_reporting/lib/redmine_reporting/sweeper.rb:16:in `around'
plugins/redmine_reporting/lib/redmine_reporting/sweeper.rb:16:in `around'
lib/redmine/sudo_mode.rb:61:in `sudo_mode'
`

**Comment by naitoh** [comment]
Sorry, Currently, rbpdf does not support webp yet.
