### ISSUE TITLE
 Incorrect characters when copying out of a generated PDF with Acrobat

### ISSUE THREAD

**Issue by YSavanier** [naitoh/rbpdf#65]
Hello

Since this commit d9613238b065f7aaf902c1ce7804ed989636c85c in version 1.19.4 PDF generated text can't be copy pasted using Adobe Acrobat Reader, only square symbols are pasted. A ticket has been opened on Redmine project see : https://www.redmine.org/issues/32740

Reverting the commit doesn't solve the issue either as the PDF become corrupted. It seems UTF-8 characters are translated to a speific unicode range  that is not the one corresponding to the standard UTF-8 characters codes.

Regards,

Y. Savanier

**Comment by naitoh** [comment]
My apologies for the delay in my response.
Fixed in #71.
