### ISSUE TITLE
Infinit loop on oversize images.

### ISSUE THREAD

**Issue by salmanmp** [naitoh/rbpdf#88]
Hi again
I found the scenario that makes an infinit loop!

```Ruby
#irb
html = '<p><img src="/somewhere/image.png" style="width:2000px;height:563px;"></p>'
r = RBPDF.new
r.add_page
r.set_rtl(true)
r.writeHTMLCell(0, 0, "", "", html)
```
If you decerase `width` to `1000px` it works fine.

As I mentioned at the first message it is related to this code block in `rbpdf.rb`. But it's not related to `src` and existance of image, but related to oversize of image (that @skalimer0 told before :+1: ).

```Ruby
if (@rtl and (@x - imgw < @l_margin + @c_margin)) or (!@rtl and (@x + imgw > @w - @r_margin - @c_margin))
    # add automatic line break
    autolinebreak = true
    Ln('', cell)
    # go back to evaluate this line break
    key -= 1
end
``` 

My Environment:
```Bash
$ruby -v
ruby 2.7.7p221 (2022-11-24 revision 168ec2b1e5) [x86_64-linux]

$gem list rbpdf
*** LOCAL GEMS ***
rbpdf (1.21.1, 1.21.0, 1.20.1)
rbpdf-font (1.19.1)

```

_Originally posted by @salmanmp in https://github.com/naitoh/rbpdf/issues/62#issuecomment-1602839180_

**Comment by naitoh** [comment]
https://github.com/naitoh/rbpdf/pull/new/fix_infinite_loop_when_rtl_true

Fixed in #89.

**Comment by salmanmp** [comment]
Thank you for resolving this.
May I ask you to publish updated gem?

**Comment by naitoh** [comment]
Please use https://rubygems.org/gems/rbpdf/versions/1.21.2

**Comment by salmanmp** [comment]
Thank you
